# Generated by Django 4.0.4 on 2022-04-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire', '0003_dictionnaire_t'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dictionnaire',
        ),
        migrations.AlterField(
            model_name='dictionnaire_t',
            name='classification',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dictionnaire_t',
            name='definition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dictionnaire_t',
            name='word',
            field=models.TextField(),
        ),
    ]
