# Generated by Django 4.0.4 on 2022-04-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire', '0004_delete_dictionnaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dictionnaire_t1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('classification', models.CharField(max_length=10)),
                ('definition', models.CharField(max_length=100)),
                ('url_image', models.URLField(default=None, max_length=50)),
                ('frequence', models.IntegerField(default=None)),
            ],
        ),
    ]
